global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval:     10s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 5s

scrape_configs:

  - job_name: 'connect'
    static_configs:
    - targets:
        - 'connect:1111'
      labels:
        env: 'dev'
        cluster: 'cluster1'