---
version: '2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
        - "./monitoring-stack/settings:/etc/prometheus/"
        command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
        - 9090:9090

    grafana:
        image: grafana/grafana:latest
        depends_on:
        - prometheus
        ports:
        - 3000:3000
        volumes:
        - "./monitoring-stack/settings:/etc/grafana/provisioning/datasources/"
        - "./monitoring-stack/settings/dashboards:/etc/grafana/provisioning/dashboards/"
        

    
